map_resolution: 0.1
robot_height: 1.5
normal_estimation_radius: 0.5
ground_normal_z_threshold: 0.9
block_size: 10.0 # 並列処理で分割するブロックのサイズ [m] (フェーズ2)

# クラスタリングパラメータ (EuclideanClusterExtraction用)
min_cluster_size: 50    # クラスタを構成する最小点数
max_cluster_size: 25000000 # クラスタを構成する最大点数

# Outlier Removal parameters (StatisticalOutlierRemoval)
outlier_removal_enable: false
outlier_removal_mean_k: 50
outlier_removal_std_dev_mul_thresh: 1.0

# Map processing parameters
free_space_kernel_size: 10
obstacle_space_kernel_size: 5

preview_map_on_exit: false # trueにすると、可能であれば終了前に地図をプレビュー表示 (現在は未実装)
