map_resolution: 0.1
robot_height: 1.5
normal_estimation_radius: 1.0
ground_normal_z_threshold: 0.7
block_size: 10.0 # 並列処理で分割するブロックのサイズ [m] (フェーズ2)

# クラスタリングパラメータ (EuclideanClusterExtraction用)
min_cluster_size: 50    # クラスタを構成する最小点数
max_cluster_size: 25000000 # クラスタを構成する最大点数

preview_map_on_exit: false # trueにすると、可能であれば終了前に地図をプレビュー表示 (現在は未実装)
